"""
Analysis router - endpoints for data processing and auto-analytics.

Phase 2 endpoints:
  POST /api/datasets/{id}/analyze   — Run the full analysis pipeline
  GET  /api/datasets/{id}/analysis  — Retrieve saved analysis results
"""

import logging
import json
import os
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from app.core.config import settings
from app.services.dataset_manager import get_dataset, update_dataset
from app.services.analysis_pipeline import load_csv, run_analysis, save_analysis_results
from app.services.dataset_profile_service import DatasetProfileService

router = APIRouter(prefix="/api", tags=["analysis"])
logger = logging.getLogger(__name__)


# ── POST /api/datasets/{id}/analyze ──────────────────────────────────────────

@router.post("/datasets/{dataset_id}/analyze")
async def analyze_dataset(dataset_id: str):
    """
    Run the full analysis pipeline on an ingested dataset.

    Steps: schema detection → cleaning → enrichment → insights → charts.
    Returns the complete analysis response.
    """
    meta = get_dataset(dataset_id)
    if not meta:
        raise HTTPException(status_code=404, detail=f"Dataset '{dataset_id}' not found")
    logger.info("Starting analysis for dataset_id=%s", dataset_id)

    # Prefer the clean CSV from ingestion, fall back to original upload
    csv_path = (
        meta.clean_csv_path
        if meta.clean_csv_path and os.path.exists(meta.clean_csv_path)
        else meta.file_path
    )

    if not csv_path or not os.path.exists(csv_path):
        raise HTTPException(status_code=404, detail="Dataset file not found on disk")

    try:
        clean_columns = None
        if meta.file_path and os.path.exists(meta.file_path):
            clean_columns = load_csv(meta.file_path).columns.tolist()

        results = run_analysis(
            csv_path,
            dataset_id=dataset_id,
            clean_output_dir=os.path.join(settings.OUTPUT_DIR, dataset_id),
            clean_filename=meta.original_filename,
            clean_columns=clean_columns,
        )

        # Save results to disk for later retrieval
        analysis_path = save_analysis_results(results, settings.OUTPUT_DIR, dataset_id)
        clean_path = results.get("clean_dataset_path") or meta.clean_csv_path
        if clean_path and os.path.exists(clean_path):
            profile_df = load_csv(clean_path)
            profile = DatasetProfileService().build(dataset_id, results, profile_df)
            DatasetProfileService().save(dataset_id, profile, settings.OUTPUT_DIR)

        # Update dataset status
        update_dataset(
            dataset_id,
            status="analyzed",
            analysis_path=analysis_path,
            clean_csv_path=clean_path,
            clean_rows=results.get("stats", {}).get("total_rows_after_cleaning", meta.clean_rows),
            embedding_status="not_started",
            embedding_model=None,
            embedding_dimension=None,
            embedding_count=0,
            embedding_index_name=None,
            embedded_at=None,
        )
        logger.info("Analysis completed for dataset_id=%s", dataset_id)

        return results

    except Exception as exc:
        logger.exception("Analysis failed for dataset_id=%s", dataset_id)
        raise HTTPException(status_code=500, detail=f"Analysis failed: {str(exc)}")


@router.get("/download/clean-dataset/{dataset_id}")
async def download_clean_dataset(dataset_id: str):
    """Download the cleaned CSV generated by the analysis pipeline."""
    meta = get_dataset(dataset_id)
    if not meta:
        raise HTTPException(status_code=404, detail=f"Dataset '{dataset_id}' not found")

    clean_path = getattr(meta, "clean_csv_path", None) or ""
    if not clean_path or not os.path.exists(clean_path):
        raise HTTPException(
            status_code=404,
            detail="Clean dataset not found. Run analysis before downloading clean data.",
        )

    download_name = f"clean_{Path(meta.original_filename).stem or 'dataset'}.csv"
    return FileResponse(
        clean_path,
        media_type="text/csv; charset=utf-8",
        filename=download_name,
    )


# ── GET /api/datasets/{id}/analysis ──────────────────────────────────────────

@router.get("/datasets/{dataset_id}/analysis")
async def get_analysis(dataset_id: str):
    """
    Retrieve previously saved analysis results for a dataset.
    """
    meta = get_dataset(dataset_id)
    if not meta:
        raise HTTPException(status_code=404, detail=f"Dataset '{dataset_id}' not found")

    # Check for saved analysis file
    analysis_path = getattr(meta, "analysis_path", None) or ""

    # Fallback: look for the file by convention
    if not analysis_path or not os.path.exists(analysis_path):
        fallback = os.path.join(settings.OUTPUT_DIR, f"{dataset_id}_analysis.json")
        if os.path.exists(fallback):
            analysis_path = fallback
        else:
            raise HTTPException(
                status_code=404,
                detail="No analysis results found. Run POST /api/datasets/{id}/analyze first.",
            )

    try:
        with open(analysis_path, "r") as f:
            return json.load(f)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to load analysis: {str(exc)}")
