/**
 * TextLens AI — API Client
 *
 * Centralised HTTP client for all backend calls.
 */

import axios from 'axios';

const API_BASE = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api';

const api = axios.create({
  baseURL: API_BASE,
  timeout: 300_000,   // 5 min — analysis on large datasets can be slow
});

// ── Ingestion ────────────────────────────────────────────────────────────────

/**
 * Upload a file and run the ingestion pipeline.
 * @param {File} file
 * @param {string|null} textColumn - Optional text column override
 * @param {function} onProgress - Axios progress callback
 * @returns {Promise<{dataset_id: string, report: object}>}
 */
export async function uploadFile(file, textColumn = null, onProgress = null) {
  const formData = new FormData();
  formData.append('file', file);

  const params = {};
  if (textColumn) params.text_column = textColumn;

  const res = await api.post('/upload', formData, {
    params,
    headers: { 'Content-Type': 'multipart/form-data' },
    onUploadProgress: onProgress,
  });
  return res.data;
}

/**
 * List all uploaded datasets.
 * @returns {Promise<{datasets: Array, total: number}>}
 */
export async function getDatasets() {
  const res = await api.get('/datasets');
  return res.data;
}

/**
 * Get a preview of a dataset's rows.
 * @param {string} datasetId
 * @param {number} limit
 * @returns {Promise<{columns: string[], rows: object[], total_rows: number, showing: number}>}
 */
export async function getDatasetPreview(datasetId, limit = 50) {
  const res = await api.get(`/datasets/${datasetId}/preview`, { params: { limit } });
  return res.data;
}

/**
 * Health check.
 * @returns {Promise<{status: string, service: string}>}
 */
export async function checkHealth() {
  const res = await api.get('/health');
  return res.data;
}


// ── Analysis ─────────────────────────────────────────────────────────────────

/**
 * Run the full analysis pipeline on a dataset.
 * @param {string} datasetId
 * @returns {Promise<object>} Full analysis response (schema, insights, charts)
 */
export async function analyzeDataset(datasetId) {
  const res = await api.post(`/datasets/${datasetId}/analyze`);
  return res.data;
}

/**
 * Get previously saved analysis results.
 * @param {string} datasetId
 * @returns {Promise<object>} Saved analysis response
 */
export async function getAnalysis(datasetId) {
  const res = await api.get(`/datasets/${datasetId}/analysis`);
  return res.data;
}

/**
 * Download the cleaned CSV generated by analysis.
 * @param {string} datasetId
 * @returns {Promise<{blob: Blob, filename: string}>}
 */
export async function downloadCleanDataset(datasetId) {
  const res = await api.get(`/download/clean-dataset/${datasetId}`, { responseType: 'blob' });
  const disposition = res.headers['content-disposition'] || '';
  const match = disposition.match(/filename="?([^"]+)"?/i);
  return {
    blob: res.data,
    filename: match?.[1] || 'clean_dataset.csv',
  };
}


// Semantic Search + QA

/**
 * Embed a cleaned dataset into the configured vector index.
 * @param {string} datasetId
 * @returns {Promise<object>}
 */
export async function embedDataset(datasetId) {
  const res = await api.post('/embed', { dataset_id: datasetId });
  return res.data;
}

/**
 * Search a dataset namespace semantically.
 * @param {string} datasetId
 * @param {string} query
 * @param {number} topK
 * @returns {Promise<object>}
 */
export async function searchDataset(datasetId, query, topK = 5) {
  const res = await api.post('/search', { dataset_id: datasetId, query, top_k: topK });
  return res.data;
}

/**
 * Ask a grounded QA question over a dataset namespace.
 * @param {string} datasetId
 * @param {string} question
 * @param {number} topK
 * @returns {Promise<object>}
 */
export async function askDatasetQuestion(datasetId, question, topK = 5) {
  const res = await api.post('/qa', { dataset_id: datasetId, question, top_k: topK });
  return res.data;
}

export default api;
